// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDicILlBp0MI1E31KGbIMGpHVLX_WYhCW4',
    appId: '1:14190723695:web:ac8417d5f0a0b93bdbc39a',
    messagingSenderId: '14190723695',
    projectId: 'lead-generator-6a493',
    authDomain: 'lead-generator-6a493.firebaseapp.com',
    storageBucket: 'lead-generator-6a493.firebasestorage.app',
    measurementId: 'G-MK8GC5MHV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9s2yW_ekWNJd3wOxqnNXyI5kHqzgozF4',
    appId: '1:14190723695:android:8b6f042dd2147091dbc39a',
    messagingSenderId: '14190723695',
    projectId: 'lead-generator-6a493',
    storageBucket: 'lead-generator-6a493.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeUg98VlIm9sY-WQnvL16fNScJ_WPYYjY',
    appId: '1:14190723695:ios:d6b1a200ed478976dbc39a',
    messagingSenderId: '14190723695',
    projectId: 'lead-generator-6a493',
    storageBucket: 'lead-generator-6a493.firebasestorage.app',
    iosBundleId: 'com.example.leadGenerator',
  );
}
